#!/bin/bash
fileext="${1}"
IFS='.' read -ra the_file <<< "$fileext"
if [ -z "${1}" ]; then
  echo "No File mentioned!!!"
else
  filename=${the_file[0]}
  ext=${the_file[1]}
  case $ext in "java" ) javaexe $filename ${2} ${3};; esac
  case $ext in "c" ) cexe $filename ${2} ${3};; esac
  case $ext in "cpp" ) cppexe $filename ${2} ${3};; esac
  case $ext in "py" ) pyexe $filename ${2} ${3};; esac
  case $ext in "asm" ) asmexe $filename ;; esac
  case $ext in "js" ) jsexe $filename ;; esac
fi;
