#!/bin/bash
echo -e "\033[0;34m\033[1mInterpreting...\033[0m"
echo -e "\033[0;32m\033[1m-----Output----------\033[0m"
echo -e ""
node ${1}.js
echo -e ""
echo -e "\033[0;32m\033[1m-----The End----------\033[0m"
