#!/bin/bash
echo -e "\033[0;34m\033[1mAssembling.....\033[0m"
if nasm -f elf "$PWD/${1}.asm\033[0m"
then
  echo -e "\033[0;34m\033[1mLinking.....\033[0m"
  if ld -m elf_i386 -s -o $1 "$PWD/${1}".o
  then
    echo -e "\033[0;34m\033[1mAssembled and linked...Executing \033[0m"
    echo -e "\033[0;32m\033[1m-----Output----------\033[0m"
    echo -e ""
    ./$1
    echo -e ""
    echo -e "\033[0;32m\033[1m-----The End----------\033[0m"
  fi
fi
