#!/bin/bash
echo -e "\033[0;34m\033[1mCompiling.... \033[0m"
if javac "$PWD/${1}.java"
then
if [ -z "${2}" ]; then
  echo -e "\033[0;34m\033[1mCompiled...Executing \033[0m"
  echo -e "\033[0;32m\033[1m----------Output----------\033[0m"
  echo -e ""
  java "${1}"
  elif [ -n "${3}" ]; then
    echo -e "\033[0;34m\033[1mCompiled...Executing \033[0m"
    java "${1}" < ${2} > "${3}"
  else
    echo -e "\033[0;34m\033[1mCompiled...Executing \033[0m"
    echo -e "\033[0;32m\033[1m----------Output----------\033[0m"
    echo -e ""
    java "${1}" < ${2}
  fi
else
echo -e "\033[0;31m\033[1mcompile time error. Couldn't execute\033[0m"
fi;
echo -e "\033[0;32m\033[1m----------The End----------\033[0m"