#!/bin/bash
echo -e "\033[0;34m\033[1mInterpreting...\033[0m"
echo -e "\033[0;32m\033[1m-----Output----------\033[0m"
echo -e ""
if [ -z "${2}" ]; then
  python ${1}.py
elif [ -n "${3}" ]; then
  python ${1}.py < "${2}" > "${3}"
else
  python ${1}.py < "${2}"
fi
echo -e ""
echo -e "\033[0;32m\033[1m-----The End----------\033[0m"
